### PR TITLE
Overhaul

### PR DESCRIPTION
**Pull request by MaxHalford**
This PR is a complete rewrite of lea. I will soon follow up with a README update.

### CODE REVIEW

**Review by MaxHalford — COMMENTED** [review]
@GitSquared your change shouldn't be necessary 🤔

The idea is that the `LEA_BQ_PROJECT_ID` env var is fed to the `BigQueryClient` in the `Conductor.make_client` method. That's where we determine where to write tables, not when we load the scripts.

**Comment by GitSquared** [comment]
@MaxHalford sorry wasn't expecting to see you active today 😛 

Indeed that was a false lead, reverted it in [`fb177e7` (#70)](https://github.com/carbonfact/lea/pull/70/commits/fb177e78189ae0fc1d2147f3bbf9c55d7746d37f)

I've added a fix in [`dd8e101` (#70)](https://github.com/carbonfact/lea/pull/70/commits/dd8e101f1349bfea1fd48fe40fe6fc7e9ea9ffec) that successfully corrects an issue experienced on Kaya where running with a compute project and a write project fails because views querying datasets without a project prefix default to trying to find their tables in the compute project.
Concretely: a view querying `kaya.x` will be interpreted as `compute-project-id.kaya.x`, instead of `write-project-id.kaya.x`.

I didn't find an easier way than regex-ing our way to `FROM` and `JOIN` statements in query codes. I thought this could be an option set on the [`QueryJob`](https://cloud.google.com/python/docs/reference/bigquery/latest/google.cloud.bigquery.job.QueryJob) but doesn't look like it.

Fix works on my side.

**Comment by MaxHalford** [comment]
Ok thanks for the explanation. Let's use your fix now, but IIRC there is a better way 👀

**Comment by MaxHalford** [comment]
I'm not able to reproduce the bug you found. Locally I set this:

```sh
LEA_WAREHOUSE=bigquery
LEA_BQ_LOCATION=EU
LEA_BQ_PROJECT_ID=int-data-kaya-dev
LEA_BQ_COMPUTE_PROJECT_ID=int-data-kaya-prod
LEA_BQ_DATASET_NAME=kaya
FREEZE_RELEASES=true
```

I go to the `int-data-kaya-dev` project in the console, and I delete the `kaya_stable_max` dataset.

I am then able to run this:

```sh
lea run --select core.users
```

Followed by this:

```sh
lea run --select core.accounts
```

The latter depends on `core.users`, and uses the one in the `int-data-kaya-dev` project, which is the `LEA_BQ_PROJECT_ID` (and not `int-data-kaya-prod` which is the `LEA_BQ_COMPUTE_PROJECT_ID`)

Can you share the exact error you're aiming to fix?

**Comment by MaxHalford** [comment]
> [fix: fields is not valid config](https://github.com/carbonfact/lea/pull/70/commits/3b2b6281e538d2c0447d6439f4262da76998e4c7)

Same, can you show me the error you got?

**Comment by MaxHalford** [comment]
Ok after looking into a bit more, I think I can guess the error you're getting. I've just pushed a change which should solve the issue, by setting the project of each dependency. This should be more robust than a regex. Let me know if it works!

**Comment by GitSquared** [comment]
@MaxHalford smart! latest version of this branch seems to run for me.

**Comment by GitSquared** [comment]
@MaxHalford fyi I see this at the end of the run:

image

**Comment by MaxHalford** [comment]
Are you sure you're up to date? I got that error a while back. On my side, I'm getting this:

> Failed running kaya_stable_max.tests.core__batches__process_batch_name#unique                                                                            
           400 POST https://bigquery.googleapis.com/bigquery/v2/projects/int-data-kaya-dev/jobs?prettyPrint=false: Label value                                      
           "core__batches__process_batch_name#unique" has invalid characters. 

Looking for a fix 👀

**Comment by GitSquared** [comment]
Fix for that is already pushed on kaya main. I ran into it too.

**Comment by GitSquared** [comment]
> Are you sure you're up to date? I got that error a while back.

Yeah just re-checked by pulling this branch and Kaya's, still have it.

**Comment by MaxHalford** [comment]
I just merged [this](https://github.com/carbonfact/kaya/pull/625/files). Try again? I believe I'm up to date on both lea and Kaya locally, and `lea run` is working

**Comment by MaxHalford** [comment]
By the way, we should probably switch to using a Python package, and not a submodule.

**Comment by GitSquared** [comment]
Just pulled Kaya + this branch on Lea submodule and `poetry install`'d, here's how it looks so far:

- `poetry run lea run --production`
	- ✅ succeeds in 53s (🤯), 189 scripts
	- I still see the `'Drop' object has no attribute 'named_selects'` messages at the end 🤷‍♂️
		- Could it be linked to the GCP projects i'm running against?
- `poetry run lea run --production --incremental account_slug demo-account`
	- ❌ crashes in 4s
	- ```
		ERRORED kaya.tests.core__accounts__ticker___unique                                                                                                                    
		           400 Syntax error: Generalized field access is not allowed in the FROM clause without UNNEST; Use UNNEST(<expression>) at [5:17]; reason: invalidQuery, location:      
		           query, message: Syntax error: Generalized field access is not allowed in the FROM clause without UNNEST; Use UNNEST(<expression>) at [5:17]                           
		           ✋ Early ending because an error occurred                                                                                                                             
		           😴 Ending session
		```

**Comment by MaxHalford** [comment]
> 'Drop' object has no attribute 'named_selects'

Ah yes, this is why I added the `fields=[]` thing. Any reason why you removed it?

**Comment by MaxHalford** [comment]
Try again with the latest commit, it should work. In the meantime I'll take a look at the incremental query.

**Comment by GitSquared** [comment]
I had an error with `fields` but can't find it anymore, sorry. Let's run with your version.

**Comment by MaxHalford** [comment]
No need to apologize! We'll figure it out :)

**Comment by GitSquared** [comment]
Tried again, `--production` is 👌✅, `--incremental` still seems to get some generalized field access error (happened while running `kaya.collect.metrics.days_since_last_batch___audit`).
Can probably fix by emulating your last commit - will do it tomorrow if you don't try first

**Comment by GitSquared** [comment]
We're getting excitingly close!

**Comment by MaxHalford** [comment]
Just came from a walk. I can reproduce the incremental issue, working on a nice fix :)

**Comment by MaxHalford** [comment]
Ok my latest commit should fix. Running the following command gives a good idea of what is happening:

```sh
lea run --incremental account_slug demo-account --print --select platform.accounts --select core.accounts --restart
```

@GitSquared have you checked out the `lea clone` command? It copies the production data to a dev dataset. In the context of the monorepo, most branches won't make changes to the SQL, so the CI will only have to run `lea clone`.

For branches that do make SQL changes, we'll want to run:

```sh
lea clone
lea run --select git+
```

Two things:

1. The nice thing about `lea run` is that it is stateful by default. If you don't use `--restart`, it will only run the views that haven't been materialized yet. I tried to make it smart: if the source code of a materialized view has been modified, lea should figure out that said view and its dependencies have to be refreshed. I said *should* because this logic is based on comparing file timestamps to BigQuery timestamps: it works locally, but I'm not sure about what happens in CI.
2. When we merge a branch, we'll want to clone the dev dataset back into production. I haven't implemented this logic yet. And as we discussed, we need to figure out the details of how this should behave in live/stable.

Don't fret, I will document this stuff once the dust has settled.

**Comment by GitSquared** [comment]
@MaxHalford I have seen `lea clone` indeed and I'm very excited about it 😁

> most branches won't make changes to the SQL, so the CI will only have to run lea clone.

In our usecase, since our backend only reads the data warehouse, we can even skip running lea altogether when there are no sql changes and just point preview environments to our live dataset, I think!

> When we merge a branch, we'll want to clone the dev dataset back into production. I haven't implemented this logic yet.

This is the main direct usage of this command I had in mind indeed. It matches what we do for software deployments across the stack, where we build a new version with a unique URL, run tests against it, then "promote" it by routing traffic to it etc.
In the data case it would be clone production to a dev dataset, refresh it, run tests, clone it back to prod.

Anything missing in the command to support the "cloning back to prod" step? I thought I could just run `lea clone` with a from dataset in dev and the target in prod.

**Comment by MaxHalford** [comment]
Yes what you just said should work in theory! It's just a question of coding it

**Pull request merged**
